"""Round-62 workflow + defensive bundle (#E61-E70 + #G78-G80).

(Renamed from `workflow.py` to avoid clash with the nuclei-style workflow
engine that already exists in `wpsecscan/workflow.py`.)

#E61 daily_digest          — alternative to weekly digest
#E62 pr_comment_body       — markdown body for the GitHub Action to post on a PR
#E63 pre_commit_hook       — git hook shell script generator
#E64 watch_mode            — re-scan on local file change (uses watchdog if avail)
#E65 companion_log_tail    — fetch the WP companion plugin's audit log
#E66 apple_shortcuts_dict  — Shortcuts.app-importable URL recipe
#E67 bookmarklet_js        — one-line JavaScript to scan current page
#E68 zsh_completion        — Zsh completion script
#E69 man_page              — groff source for `man wpsecscan`
#E70 auto_resume_marker    — checkpoint helper for GUI auto-resume

#G78 siem_forward          — push every finding into Splunk HEC / Elastic / Loki live
#G79 honeypot_deploy       — companion-plugin-driven honeypot deployment guide
#G80 — see egress_recorder.py (round-62 #B26+#G80 lives there already)
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError


# ---- #E61 daily digest ----

def render_daily_digest(sites: list[dict]) -> str:
    """Daily summary — only sites with NEW critical/high in the last 24h."""
    cutoff = int(time.time()) - 86400
    lines = ["WPSecScan daily digest", "=" * 40, ""]
    any_new = False
    for s in sites or []:
        ts = int(s.get("last_scan_ts") or 0)
        if ts < cutoff:
            continue
        c = int(s.get("last_critical") or 0)
        h = int(s.get("last_high") or 0)
        if c == 0 and h == 0:
            continue
        any_new = True
        lines.append(f"  {s.get('url', '?')}")
        lines.append(f"    NEW critical={c} high={h}  "
                       f"(scanned {time.strftime('%H:%M', time.localtime(ts))})")
    if not any_new:
        lines.append("  No new critical/high findings in the last 24h.")
    return "\n".join(lines)


# ---- #E62 PR comment body ----

def pr_comment_body(report: Any, *, baseline_critical: int = 0,
                      baseline_high: int = 0) -> str:
    d = report.to_dict() if hasattr(report, "to_dict") else (report or {})
    s = d.get("summary", {})
    cur_crit, cur_high = int(s.get("critical", 0)), int(s.get("high", 0))
    delta_crit = cur_crit - baseline_critical
    delta_high = cur_high - baseline_high
    icon = "[OK]" if delta_crit <= 0 and delta_high <= 0 else "[WARN]"
    return (
        f"## {icon} WPSecScan - {d.get('target', '?')}\n\n"
        f"| Severity | Count | Delta vs baseline |\n"
        f"|---|---|---|\n"
        f"| Critical | {cur_crit} | {'+' if delta_crit > 0 else ''}{delta_crit} |\n"
        f"| High | {cur_high} | {'+' if delta_high > 0 else ''}{delta_high} |\n"
        f"| Medium | {s.get('medium', 0)} | - |\n"
        f"| Low | {s.get('low', 0)} | - |\n\n"
        f"Risk score: **{d.get('risk_score', 0)}/100**\n\n"
        f"_Generated by [WPSecScan](https://github.com/bryanflowers/wpsecscan)._"
    )


# ---- #E63 pre-commit hook ----

def pre_commit_hook_script() -> str:
    return r"""#!/bin/sh
# WPSecScan pre-commit hook
# Install: cp this to .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
set -e
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(php|js)$" || true)
[ -z "$STAGED" ] && exit 0
FAIL=0
for f in $STAGED; do
  case "$f" in
    *wp-content/plugins/*|*wp-content/themes/*) ;;
    *) continue ;;
  esac
  if grep -nE "(passthru|system|shell_exec|popen|exec)\s*\(\s*\\\$_" "$f" >/dev/null 2>&1; then
    echo "BLOCKED: $f has shell-exec on \$_GET/POST/REQUEST input."
    FAIL=1
  fi
  if grep -nE "(eval|assert)\s*\(\s*\\\$_" "$f" >/dev/null 2>&1; then
    echo "BLOCKED: $f has eval() on user input."
    FAIL=1
  fi
done
[ $FAIL -ne 0 ] && { echo "Bypass with --no-verify (NOT RECOMMENDED)"; exit 1; }
exit 0
"""


# ---- #E64 watch mode ----

def watch_directory(path: str, *, on_change, debounce_s: float = 1.0) -> None:
    """Block + call `on_change(changed_path)` when files modified."""
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        print("Watch mode needs: pip install watchdog", file=sys.stderr)
        return
    last_fired: dict[str, float] = {}

    class _H(FileSystemEventHandler):
        def on_any_event(self, event) -> None:
            if event.is_directory:
                return
            now = time.monotonic()
            if now - last_fired.get(event.src_path, 0) < debounce_s:
                return
            last_fired[event.src_path] = now
            try:
                on_change(event.src_path)
            except Exception as e:  # noqa: BLE001
                print(f"watch handler error: {e}", file=sys.stderr)

    obs = Observer()
    obs.schedule(_H(), path, recursive=True)
    obs.start()
    try:
        while True:
            time.sleep(0.5)
    except KeyboardInterrupt:
        obs.stop()
    obs.join()


# ---- #E65 companion log tail ----

def companion_log_tail(target_url: str, *, companion_token: str,
                        last_n: int = 50) -> list[dict]:
    if os.environ.get("WPSECSCAN_NO_NETWORK"):
        return []
    from urllib.parse import urlparse
    parsed = urlparse(target_url)
    base = f"{parsed.scheme}://{parsed.netloc}"
    req = urllib.request.Request(
        f"{base}/wp-json/wpsecscan/v1/activity-log?n={int(last_n)}",
        headers={"X-WPSecScan-Token": companion_token,
                  "User-Agent": "WPSecScan/companion-log-tail"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            if r.status != 200:
                return []
            data = json.loads(r.read().decode("utf-8", errors="replace"))
        return data if isinstance(data, list) else []
    except (HTTPError, URLError, OSError, ValueError):
        return []


# ---- #E66 Apple Shortcuts ----

def apple_shortcuts_recipe(default_target: str = "https://example.com") -> dict:
    return {
        "name": "Scan with WPSecScan",
        "actions": [
            {"identifier": "is.workflow.actions.gettext",
              "parameters": {"text": default_target}},
            {"identifier": "is.workflow.actions.openurl",
              "parameters": {"url_template": "wpsecscan://scan?target={{Text}}"}},
        ],
        "notes": "Add to Share Sheet for one-tap scanning of any URL from Safari.",
    }


# ---- #E67 bookmarklet ----

_BOOKMARKLET_API_BASE_RE = __import__("re").compile(r"^https?://[A-Za-z0-9.\-]+(?::\d{1,5})?(?:/[A-Za-z0-9._\-/]*)?$")


def bookmarklet_js(api_base: str = "http://localhost:8765") -> str:
    """Return a one-line JS bookmarklet that POSTs the current page URL
    to the local WPSecScan API server.

    `api_base` is regex-validated to prevent JS injection via crafted input
    like `javascript://alert(1)`. On failure returns an empty string.
    """
    api_base = (api_base or "").rstrip("/")
    if not _BOOKMARKLET_API_BASE_RE.match(api_base):
        return ""
    return (
        "javascript:(()=>{const u=location.href;"
        f"fetch('{api_base}/scan',{{method:'POST',headers:{{'Content-Type':'application/json'}},"
        "body:JSON.stringify({target:u})})"
        ".then(r=>r.ok?alert('Scan queued for '+u):alert('Scan failed: '+r.status))"
        ".catch(e=>alert('Cannot reach WPSecScan API. Start with: wpsecscan api-server'));})();"
    )


# ---- #E68 zsh completion ----

def zsh_completion() -> str:
    return r"""#compdef wpsecscan
_wpsecscan() {
    local -a sub
    sub=(
        'sites:Manage tracked sites'
        'schedule:Manage scheduled scans'
        'digest:Configure weekly/daily digest'
        'db:Manage vulnerability DB + subscriptions'
        'ai-cost:Show AI backend cost log'
    )
    _arguments -C '1: :->sub' '*: :->args'
    case "$state" in
      sub) _describe 'subcommand' sub ;;
      args)
        case "$words[2]" in
          sites)    _values 'action' add list remove scan ;;
          schedule) _values 'action' install uninstall pause resume status ;;
          digest)   _values 'action' configure test send ;;
          db)       _values 'action' status update subscribe unsubscribe signatures alert-check ;;
          *) _arguments \
              '--target[URL]:url' \
              '--aggressive[Enable active payloads]' \
              '--auth-user[Admin username]:user' \
              '--auth-app-password[WP App Password]:password' \
              '--companion-token[Companion token]:token' \
              '--proxy[Proxy URL]:proxy' \
              '--proxy-auth[user:pass]:auth' \
              '--demo[Demo scan]' '--no-ai[Disable AI]' '--version[Version]' ;;
        esac ;;
    esac
}
compdef _wpsecscan wpsecscan
"""


# ---- #E69 man page ----

def man_page() -> str:
    return r""".TH WPSECSCAN 1 "2026" "WPSecScan 2.0" "Security tools"
.SH NAME
wpsecscan \- defensive WordPress security scanner
.SH SYNOPSIS
.B wpsecscan
[\fIOPTIONS\fR] \fITARGET_URL\fR
.PP
.B wpsecscan
.RB { sites | schedule | digest | db | ai-cost }
.SH DESCRIPTION
WPSecScan runs 150+ defensive security checks against a WordPress site.
Use only on sites you own or have explicit written permission to test.
.SH OPTIONS
.TP
.B \-\-target \fIURL\fR
URL of the WordPress site to scan.
.TP
.B \-\-aggressive
Enable active-payload checks. Owned sites only.
.TP
.B \-\-auth\-user \fIUSER\fR \-\-auth\-pass \fIPASSWORD\fR
Authenticate via the cookie / wp\-login.php flow.
.TP
.B \-\-auth\-app\-password \fIPASSWORD\fR
Authenticate via a WordPress Application Password (5.6+, preferred).
.TP
.B \-\-companion\-token \fITOKEN\fR
Use the WPSecScan companion plugin for richest data.
.TP
.B \-\-proxy \fIURL\fR
HTTP / HTTPS / SOCKS5 proxy.
.TP
.B \-\-proxy\-auth \fIUSER\fR:\fIPASS\fR
Proxy credentials (URL\-encoded automatically).
.TP
.B \-\-no\-ai
Hard\-disable AI helpers (same as WPSECSCAN_NO_AI=1).
.SH SUBCOMMANDS
.TP
.B sites \fI{add|list|remove|scan}\fR
Manage tracked sites for scheduled scans.
.TP
.B schedule \fI{install|uninstall|pause|resume|status}\fR
Manage weekly + daily DB refresh tasks.
.TP
.B db \fI{status|update|subscribe|unsubscribe|signatures|alert-check}\fR
Refresh CVE database, subscribe to new-CVE webhooks.
.SH ENVIRONMENT
.TP
.B WPSECSCAN_HOME
Override the config dir (default \fI~/.wpsecscan\fR).
.TP
.B WPSECSCAN_NO_AI
Hard\-disable AI features.
.TP
.B WPSECSCAN_NO_NETWORK
Air\-gapped mode.
.SH AUTHOR
Bryan <bryaninbangkok@gmail.com>
.SH "REPORTING BUGS"
https://github.com/bryanflowers/wpsecscan/issues
.SH COPYRIGHT
AGPLv3+. See https://www.gnu.org/licenses/agpl-3.0.html.
"""


# ---- #E70 auto-resume marker ----

def _home() -> Path:
    return Path(os.environ.get("WPSECSCAN_HOME") or (Path.home() / ".wpsecscan"))


def write_resume_marker(target: str, completed_check_ids: list[str]) -> None:
    p = _home() / "resume_marker.json"
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        if p.is_symlink():
            p.unlink()
        p.write_text(json.dumps({"target": target,
                                    "completed": completed_check_ids,
                                    "ts": int(time.time())}), encoding="utf-8")
    except OSError:
        pass


def load_resume_marker() -> dict | None:
    p = _home() / "resume_marker.json"
    if not p.exists() or p.is_symlink():
        return None
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
        return d if isinstance(d, dict) else None
    except (OSError, json.JSONDecodeError):
        return None


def clear_resume_marker() -> None:
    p = _home() / "resume_marker.json"
    if p.exists() and not p.is_symlink():
        try:
            p.unlink()
        except OSError:
            pass


# ============================================================
# Defensive (G78-G80)
# ============================================================

def siem_forward(report: Any, *, endpoint: str, kind: str = "splunk-hec",
                  token: str = "") -> dict:
    """Forward findings to a SIEM. kind ∈ {splunk-hec, elastic, loki, generic}."""
    if os.environ.get("WPSECSCAN_NO_NETWORK"):
        return {"ok": False, "error": "WPSECSCAN_NO_NETWORK"}
    d = report.to_dict() if hasattr(report, "to_dict") else (report or {})
    target = d.get("target", "")
    events: list[dict] = []
    for r in d.get("results", []) or []:
        cid = r.get("check_id", "?")
        for f in r.get("findings", []) or []:
            events.append({
                "ts": int(time.time()),
                "source": "wpsecscan",
                "target": target,
                "check_id": cid,
                "severity": f.get("severity"),
                "title": f.get("title"),
                "url": f.get("url"),
            })

    if kind == "splunk-hec":
        body = "\n".join(json.dumps({"event": e}) for e in events)
        headers = {"Authorization": f"Splunk {token}"} if token else {}
    elif kind == "elastic":
        lines = []
        for e in events:
            lines.append(json.dumps({"index": {"_index": "wpsecscan"}}))
            lines.append(json.dumps(e))
        body = "\n".join(lines) + "\n"
        headers = {"Content-Type": "application/x-ndjson"}
        if token:
            headers["Authorization"] = f"ApiKey {token}"
    elif kind == "loki":
        body = json.dumps({"streams": [{"stream": {"app": "wpsecscan"},
                                            "values": [[str(int(time.time() * 1e9)), json.dumps(e)]
                                                       for e in events]}]})
        headers = {"Content-Type": "application/json"}
        if token:
            headers["Authorization"] = f"Bearer {token}"
    else:
        body = "\n".join(json.dumps(e) for e in events)
        headers = {"Content-Type": "application/x-ndjson"}
        if token:
            headers["Authorization"] = f"Bearer {token}"

    req = urllib.request.Request(endpoint, data=body.encode("utf-8"),
                                   method="POST",
                                   headers={"User-Agent": "WPSecScan/siem_forward",
                                              **headers})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            return {"ok": r.status < 300, "status": r.status, "events": len(events)}
    except (HTTPError, URLError, OSError) as e:
        return {"ok": False, "error": str(e), "events": len(events)}


def honeypot_deploy_instructions(target_url: str) -> str:
    return (
        f"WPSecScan honeypot deploy for {target_url}\n"
        f"{'=' * 60}\n\n"
        f"1. Install the WPSecScan companion plugin v1.1+\n"
        f"2. WP admin -> Settings -> WPSecScan -> 'Deploy login honeypot' button\n"
        f"3. The button creates wp-admin-login.php at the WordPress root\n"
        f"   serving a fake login form. Every POST is logged.\n"
        f"4. Tail the log via `wpsecscan db alert-check`.\n"
        f"5. Auto-block hits via your firewall (Cloudflare WAF / fail2ban).\n"
    )
