"""Round-60 — consolidated tooling module covering features that don't
warrant their own file:

#6  public_history_page    — shareable HTML history per site
#7  diff_reports           — wrapper over reporters/diff (already exists)
#8  pdf_with_logo          — PDF report with company branding
#10 marketplace_patch_for  — "patched in vX.Y.Z" lookup against bundled marketplace
#11 time_machine_replay    — re-score a current scan against a past CVE-DB snapshot
#12 compare_three          — 3-site side-by-side HTML report
#13 bandwidth_limit        — context-mgr rate-limiter for HTTP calls
#16 bounty_autofill        — pre-fill HackerOne / Bugcrowd web form params
#21 emit_terraform / emit_ansible — fix-as-code stubs
#27 lockout_recovery       — auto-unlock via wp-cli (subprocess + ssh)
"""
from __future__ import annotations

import asyncio
import datetime
import hashlib
import html
import json
import os
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlencode


def _home() -> Path:
    return Path(os.environ.get("WPSECSCAN_HOME") or (Path.home() / ".wpsecscan"))


# ---- #6 public history page ----

def public_history_page(target: str, history: list[dict]) -> str:
    """Self-contained HTML page showing risk-score trend + last 10 scans.
    No JS dependencies. Caller decides where to publish it."""
    safe_target = html.escape(target)
    rows = []
    for entry in (history or [])[-10:]:
        ts = entry.get("ts", 0)
        when = time.strftime("%Y-%m-%d", time.localtime(ts)) if ts else "?"
        rows.append(
            f"<tr><td>{html.escape(when)}</td>"
            f"<td>{int(entry.get('risk', 0))}</td>"
            f"<td>{int(entry.get('critical', 0))}</td>"
            f"<td>{int(entry.get('high', 0))}</td></tr>"
        )
    sparkline = ""
    pts = [int(e.get("risk", 0)) for e in (history or [])[-30:]]
    if pts:
        coords = " ".join(f"{i * 10},{100 - p}" for i, p in enumerate(pts))
        sparkline = (f'<svg width="{len(pts) * 10}" height="100" stroke="#06f" fill="none">'
                       f'<polyline points="{coords}" stroke-width="2"/></svg>')
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>WPSecScan history — {safe_target}</title>
<style>body{{font-family:system-ui;max-width:720px;margin:2em auto;color:#222}}
table{{border-collapse:collapse;width:100%}}td,th{{padding:.4em .6em;border-bottom:1px solid #eee;text-align:left}}
.high{{color:#c00}}.med{{color:#f80}}</style></head>
<body><h1>WPSecScan history — {safe_target}</h1>
<p>Last 30 scans (risk score, lower is better):</p>{sparkline}
<table><thead><tr><th>Date</th><th>Risk</th><th>Critical</th><th>High</th></tr></thead>
<tbody>{''.join(rows) or '<tr><td colspan=4><em>no history yet</em></td></tr>'}</tbody></table>
<p style="color:#888;font-size:.9em">Generated by <a href="https://github.com/bryanflowers/wpsecscan">WPSecScan</a>.</p>
</body></html>"""


# ---- #7 diff (delegate to existing diff.py if present) ----

def diff_reports(old_path: str, new_path: str) -> dict:
    """Returns {added: list, removed: list, unchanged: int}."""
    try:
        old = json.loads(Path(old_path).read_text(encoding="utf-8")).get("results", [])
        new = json.loads(Path(new_path).read_text(encoding="utf-8")).get("results", [])
    except (OSError, ValueError, json.JSONDecodeError):
        return {"added": [], "removed": [], "unchanged": 0}

    def _key(f: dict, cid: str) -> str:
        return f"{cid}|{f.get('severity')}|{f.get('title')}|{f.get('url', '')}"

    old_keys: set[str] = set()
    new_keys: set[str] = set()
    old_finds: dict[str, dict] = {}
    new_finds: dict[str, dict] = {}
    for r in old:
        cid = r.get("check_id", "?")
        for f in r.get("findings", []):
            k = _key(f, cid)
            old_keys.add(k)
            old_finds[k] = {"check_id": cid, **f}
    for r in new:
        cid = r.get("check_id", "?")
        for f in r.get("findings", []):
            k = _key(f, cid)
            new_keys.add(k)
            new_finds[k] = {"check_id": cid, **f}
    return {
        "added":     [new_finds[k] for k in (new_keys - old_keys)],
        "removed":   [old_finds[k] for k in (old_keys - new_keys)],
        "unchanged": len(old_keys & new_keys),
    }


# ---- #8 PDF with logo ----

def pdf_with_logo(report: Any, out_pdf: str, *, logo_path: str | None = None,
                    company_name: str = "") -> str:
    """Generates a branded executive PDF. Requires `reportlab` (in the
    [pdf] extra). Returns the path on success or "" on failure.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.pdfgen import canvas
        from reportlab.lib.utils import ImageReader
    except ImportError:
        return ""
    d = report.to_dict() if hasattr(report, "to_dict") else (report if isinstance(report, dict) else {})
    out = Path(out_pdf)
    out.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(out), pagesize=A4)
    width, height = A4

    # Header (logo + company)
    if logo_path and Path(logo_path).is_file():
        try:
            c.drawImage(ImageReader(logo_path), 2 * cm, height - 4 * cm,
                          width=4 * cm, height=2 * cm, preserveAspectRatio=True, mask='auto')
        except Exception:  # noqa: BLE001
            pass
    if company_name:
        c.setFont("Helvetica-Bold", 16)
        c.drawString(8 * cm, height - 2.5 * cm, company_name)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(2 * cm, height - 5 * cm, "WPSecScan Executive Report")
    c.setFont("Helvetica", 12)
    c.drawString(2 * cm, height - 6 * cm, f"Target: {d.get('target', '?')}")
    c.drawString(2 * cm, height - 6.5 * cm, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")

    # Summary box
    s = d.get("summary", {})
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2 * cm, height - 8 * cm, f"Risk score: {d.get('risk_score', 0)}/100")
    y = height - 9 * cm
    for sev, label in (("critical", "Critical"), ("high", "High"),
                        ("medium", "Medium"), ("low", "Low")):
        c.setFont("Helvetica", 11)
        c.drawString(2 * cm, y, f"{label}: {s.get(sev, 0)}")
        y -= 0.5 * cm

    # Top critical findings
    y -= 1 * cm
    c.setFont("Helvetica-Bold", 13)
    c.drawString(2 * cm, y, "Top critical findings:")
    y -= 0.6 * cm
    c.setFont("Helvetica", 10)
    count = 0
    for r in d.get("results", []) or []:
        for f in r.get("findings", []) or []:
            if (f.get("severity") or "").lower() != "critical":
                continue
            c.drawString(2.3 * cm, y, ("• " + (f.get("title") or ""))[:90])
            y -= 0.4 * cm
            count += 1
            if count >= 10 or y < 3 * cm:
                break
        if count >= 10 or y < 3 * cm:
            break

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2 * cm, 1.5 * cm, "Confidential — generated by WPSecScan.")
    c.save()
    return str(out)


# ---- #10 marketplace patch lookup ----

def marketplace_patch_for(plugin_slug: str, vulnerable_version: str) -> str:
    """Returns the 'patched in vX.Y.Z' string from the bundled marketplace
    data. Empty if unknown."""
    if not plugin_slug:
        return ""
    p = Path(__file__).parent / "data" / "marketplace.json"
    if not p.exists():
        return ""
    try:
        market = json.loads(p.read_text(encoding="utf-8")) or {}
    except (OSError, ValueError):
        return ""
    entry = market.get(plugin_slug) or {}
    patched = entry.get("patched_in")
    if not patched:
        return ""
    return f"Patched in v{patched}" if patched else ""


# ---- #11 time-machine: re-score against snapshot ----

def time_machine_replay(report_json_path: str, cve_db_snapshot_path: str) -> dict:
    """Compare current findings against an older CVE-DB snapshot to identify
    which findings would have existed at that time. Returns {newly_introduced,
    pre_existing}."""
    try:
        report = json.loads(Path(report_json_path).read_text(encoding="utf-8"))
        snap = json.loads(Path(cve_db_snapshot_path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"newly_introduced": [], "pre_existing": []}
    known_cves = {c.get("id") for c in (snap.get("cves") or []) if isinstance(c, dict)}
    newly = []
    existing = []
    for r in report.get("results", []) or []:
        for f in r.get("findings", []) or []:
            cve_ids = re.findall(r"CVE-\d{4}-\d{4,7}", f.get("evidence", "") + " " + f.get("title", ""))
            for cid in cve_ids:
                if cid in known_cves:
                    existing.append({"cve": cid, "title": f.get("title")})
                else:
                    newly.append({"cve": cid, "title": f.get("title")})
    return {"newly_introduced": newly, "pre_existing": existing}


# ---- #12 compare three sites side-by-side ----

def compare_three(reports: list[Any]) -> str:
    """3-up HTML comparison page."""
    rows = []
    for rep in reports[:3]:
        d = rep.to_dict() if hasattr(rep, "to_dict") else (rep or {})
        s = d.get("summary", {})
        rows.append({
            "target": d.get("target", "?"),
            "risk":   d.get("risk_score", 0),
            "crit":   s.get("critical", 0),
            "high":   s.get("high", 0),
            "med":    s.get("medium", 0),
            "low":    s.get("low", 0),
        })
    head = "<th></th>" + "".join(f"<th>{html.escape(r['target'])}</th>" for r in rows)
    def row(name: str, key: str) -> str:
        return f"<tr><td><b>{name}</b></td>" + "".join(f"<td>{r[key]}</td>" for r in rows) + "</tr>"
    return f"""<!doctype html><html><head><meta charset='utf-8'>
<title>WPSecScan compare</title><style>body{{font-family:system-ui;max-width:960px;margin:2em auto}}
table{{border-collapse:collapse;width:100%}}th,td{{padding:.5em .8em;border-bottom:1px solid #eee;text-align:left}}
</style></head><body><h1>WPSecScan — side-by-side</h1>
<table><thead><tr>{head}</tr></thead><tbody>
{row('Risk', 'risk')}{row('Critical', 'crit')}{row('High', 'high')}{row('Medium', 'med')}{row('Low', 'low')}
</tbody></table></body></html>"""


# ---- #13 bandwidth limit ----

class RateLimit:
    """Async-aware sliding-window RPS limiter. Use as `async with RateLimit(rps=5):`."""
    def __init__(self, rps: float = 5.0) -> None:
        self.interval = 1.0 / max(0.1, float(rps))
        self._last = 0.0

    async def __aenter__(self) -> None:
        now = time.monotonic()
        sleep_for = self._last + self.interval - now
        if sleep_for > 0:
            await asyncio.sleep(sleep_for)
        self._last = time.monotonic()

    async def __aexit__(self, *_a) -> None:
        pass


# ---- #16 bounty autofill ----

def hackerone_autofill_url(program_handle: str, finding: dict) -> str:
    """Pre-fill a HackerOne new-report URL with title + description."""
    title = (finding.get("title") or "")[:140]
    body = (
        f"## Summary\n{finding.get('title', '')}\n\n"
        f"## Steps to reproduce\n1. Visit {finding.get('url', '?')}\n"
        f"2. Observe: {(finding.get('evidence') or '')[:1500]}\n\n"
        f"## Impact\n{finding.get('severity', '?').upper()}\n\n"
        f"## Remediation\n{(finding.get('remediation') or '')[:1500]}\n\n"
        f"_Discovered with [WPSecScan](https://github.com/bryanflowers/wpsecscan)._"
    )
    return f"https://hackerone.com/{program_handle}/reports/new?" + urlencode({"title": title, "vulnerability_information": body})


def bugcrowd_autofill_url(program_handle: str, finding: dict) -> str:
    return (
        f"https://bugcrowd.com/{program_handle}/submissions/new?" +
        urlencode({
            "title": (finding.get("title") or "")[:140],
            "description": (finding.get("evidence") or "")[:1500],
            "remediation": (finding.get("remediation") or "")[:1500],
        })
    )


# ---- #21 fix-as-code: Terraform + Ansible emit ----

def emit_terraform(finding: dict) -> str:
    """If the finding is a known-shape misconfig, emit a Terraform snippet.
    Currently covers: TLS-headers (Cloudflare zone settings)."""
    title = (finding.get("title") or "").lower()
    if "security headers" in title or "tls" in title:
        return ('resource "cloudflare_zone_settings_override" "harden" {\n'
                 '  zone_id = var.zone_id\n'
                 '  settings { security_header { enabled = true } }\n'
                 '}\n')
    return ""


def emit_ansible(finding: dict) -> str:
    title = (finding.get("title") or "").lower()
    if "wp-config" in title or "debug" in title:
        return ("- name: harden wp-config\n"
                 "  ansible.builtin.lineinfile:\n"
                 "    path: /var/www/html/wp-config.php\n"
                 "    regexp: \"define\\\\( ?'WP_DEBUG'.*\\\\)\"\n"
                 "    line: \"define('WP_DEBUG', false);\"\n")
    return ""


# ---- #27 lockout recovery (via wp-cli over ssh) ----

_SSH_TARGET_RE = re.compile(r"^[a-zA-Z0-9._\-]+@[a-zA-Z0-9.\-]+(?::\d+)?$")


def lockout_recovery(ssh_target: str, user_login: str) -> dict:
    """Use wp-cli over ssh to remove the lockout (Wordfence / iThemes) for
    the given user. Returns {ok: bool, detail: str}.

    ssh_target must match `user@host[:port]` — anything else is rejected
    to prevent argument injection.
    """
    if not _SSH_TARGET_RE.match(ssh_target or ""):
        return {"ok": False, "detail": "invalid ssh target — expected user@host"}
    if not user_login or not re.match(r"^[A-Za-z0-9._\-]+$", user_login):
        return {"ok": False, "detail": "invalid user_login"}
    if not shutil.which("ssh"):
        return {"ok": False, "detail": "ssh not on PATH"}
    cmd = [
        "ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=accept-new",
        ssh_target,
        f"wp user meta delete {user_login} wfls_lockout_until "
        f"&& wp user meta delete {user_login} itsec_lockouts",
    ]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        return {"ok": r.returncode == 0,
                 "detail": (r.stdout or "") + (r.stderr or "")[:200]}
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
        return {"ok": False, "detail": str(e)}
