"""N40 Customer-facing attestation PDF.

A one-page "we scanned this on $date and the result was OK" deliverable that
SaaS providers hand to enterprise customers as proof they're running
recurring security scans.

Differs from exec_pdf:
  - Doesn't disclose findings (just summary counts + grade + risk score)
  - Includes a signature block + scan ID for tamper-evident referencing
  - Uses the customer's brand name (if provided) in the header

Like exec_pdf, uses reportlab when installed, falls back to print-friendly HTML.
"""
from __future__ import annotations

import hashlib
import html as _html
from datetime import datetime
from pathlib import Path

from ..models import ScanReport


def _scan_id(report: ScanReport) -> str:
    """Derive a stable per-scan ID by hashing target + scanned_at."""
    h = hashlib.sha256(f"{report.target}|{report.scanned_at}".encode("utf-8")).hexdigest()
    return h[:16].upper()


def _has_reportlab() -> bool:
    try:
        import reportlab  # noqa: F401
        return True
    except ImportError:
        return False


def _html_fallback(report: ScanReport, *, vendor: str, customer: str | None) -> str:
    from ..risk import risk_grade
    score = report.risk_score
    grade = risk_grade(score)
    s = report.summary
    sid = _scan_id(report)
    today = datetime.now().strftime("%Y-%m-%d")
    return f"""<!doctype html>
<html><head><meta charset="utf-8">
<title>Security scan attestation — {_html.escape(vendor)}</title>
<style>
  @page {{ size: letter; margin: 0.8in; }}
  body {{ font-family: Georgia, serif; color: #1a1a1a; margin: 0; padding: 36px 48px; }}
  h1 {{ font-size: 26pt; margin: 0 0 4px; }}
  h2 {{ font-size: 12pt; margin: 28px 0 8px; border-bottom: 1px solid #999; padding-bottom: 4px; }}
  .vendor {{ font-size: 12pt; color: #555; }}
  .body {{ font-size: 11pt; line-height: 1.6; }}
  .stat-row {{ display: flex; gap: 18px; margin: 18px 0; }}
  .stat {{ flex: 1; border: 1px solid #ccc; padding: 14px; text-align: center; border-radius: 4px; }}
  .stat .n {{ font-size: 24pt; font-weight: 700; display: block; }}
  .stat .l {{ font-size: 9pt; text-transform: uppercase; color: #555; }}
  .sigblock {{ margin-top: 42px; border-top: 1px solid #999; padding-top: 20px; font-size: 10pt; }}
  .sigblock .scanid {{ font-family: monospace; background: #f0f0f0; padding: 2px 6px; border-radius: 2px; }}
  .footer {{ position: fixed; bottom: 24px; left: 48px; right: 48px; font-size: 9pt; color: #888; text-align: center; }}
</style></head><body>
<h1>Security scan attestation</h1>
<div class="vendor">Issued by: <b>{_html.escape(vendor)}</b>{(' &nbsp;·&nbsp; For: <b>' + _html.escape(customer) + '</b>') if customer else ''}</div>
<div class="vendor">Date issued: <b>{today}</b></div>

<h2>Statement</h2>
<div class="body">
This document attests that the production system identified below was scanned
on the date shown using WPSecScan, an automated defensive security scanner.
No findings, evidence, or remediation details are disclosed in this attestation;
the full report is retained internally by <b>{_html.escape(vendor)}</b>.
</div>

<h2>Scope</h2>
<div class="body">Target: <code>{_html.escape(report.target)}</code><br>
Scan timestamp (UTC): <code>{_html.escape(report.scanned_at)}</code><br>
Scan duration: {report.duration_ms} ms</div>

<h2>Summary</h2>
<div class="stat-row">
  <div class="stat"><span class="n">{score}</span><span class="l">Risk score / 100</span></div>
  <div class="stat"><span class="n">{grade}</span><span class="l">Grade</span></div>
  <div class="stat"><span class="n">{s.get('critical',0) + s.get('high',0)}</span><span class="l">Critical + High</span></div>
  <div class="stat"><span class="n">{sum(s.values())}</span><span class="l">Total findings</span></div>
</div>

<div class="sigblock">
Scan ID: <span class="scanid">{sid}</span> (reference this ID when requesting the full report)<br><br>
Signed for {_html.escape(vendor)}: ____________________________________________
&nbsp;&nbsp;&nbsp; Date: ______________
</div>

<div class="footer">Generated by WPSecScan — defensive security scan attestation.</div>
</body></html>"""


def _reportlab_pdf(report: ScanReport, path: Path, *, vendor: str, customer: str | None) -> None:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.colors import HexColor
    from ..risk import risk_grade

    score = report.risk_score
    grade = risk_grade(score)
    s = report.summary
    sid = _scan_id(report)
    today = datetime.now().strftime("%Y-%m-%d")

    styles = getSampleStyleSheet()
    title = ParagraphStyle("title", parent=styles["Title"], fontSize=22, spaceAfter=4)
    sub = ParagraphStyle("sub", parent=styles["BodyText"], fontSize=10, textColor=HexColor("#555555"))
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14, spaceAfter=8)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, spaceBefore=18, spaceAfter=4)

    doc = SimpleDocTemplate(str(path), pagesize=letter,
                            leftMargin=0.8 * inch, rightMargin=0.8 * inch,
                            topMargin=0.7 * inch, bottomMargin=0.7 * inch)
    flow = [
        Paragraph("Security scan attestation", title),
        Paragraph(f"Issued by: <b>{_html.escape(vendor)}</b>"
                  + (f" &nbsp;·&nbsp; For: <b>{_html.escape(customer)}</b>" if customer else ""), sub),
        Paragraph(f"Date issued: <b>{today}</b>", sub),
        Paragraph("Statement", h2),
        Paragraph(
            "This document attests that the production system identified below was scanned on the date "
            "shown using WPSecScan, an automated defensive security scanner. No findings, evidence, or "
            "remediation details are disclosed in this attestation; the full report is retained internally "
            f"by <b>{_html.escape(vendor)}</b>.", body),
        Paragraph("Scope", h2),
        Paragraph(f"Target: <code>{_html.escape(report.target)}</code><br/>"
                  f"Scan timestamp (UTC): <code>{_html.escape(report.scanned_at)}</code><br/>"
                  f"Scan duration: {report.duration_ms} ms", body),
        Paragraph("Summary", h2),
    ]
    stats = Table(
        [["Risk score", "Grade", "Critical + High", "Total findings"],
         [f"{score}/100", grade, str(s.get("critical", 0) + s.get("high", 0)), str(sum(s.values()))]],
        colWidths=[1.6 * inch] * 4,
    )
    stats.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#f0f0f0")),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, 1), 18),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.4, HexColor("#999999")),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
    ]))
    flow.append(stats)
    flow.append(Spacer(1, 0.3 * inch))
    flow.append(Paragraph(f"Scan ID: <font face='Courier'>{sid}</font>", body))
    flow.append(Paragraph(
        "Signed for " + _html.escape(vendor) + ": ____________________________________ &nbsp; Date: ______________",
        body,
    ))
    doc.build(flow)


def write(report: ScanReport, path: Path, *, vendor: str = "WPSecScan",
          customer: str | None = None) -> None:
    """Write a customer-facing attestation. PDF if reportlab, HTML otherwise."""
    if _has_reportlab():
        _reportlab_pdf(report, path, vendor=vendor, customer=customer)
        try:
            from .. import activity as _act
            _act.emit("reporter", f"Attestation PDF: {path.name}")
        except (ImportError, OSError):
            pass
        return
    html_path = path.with_suffix(".html")
    # v2.8.3 H3 — atomic temp+rename via shared helper.
    from . import _atomic_write_text
    _atomic_write_text(html_path, _html_fallback(report, vendor=vendor, customer=customer))
    try:
        from .. import activity as _act
        _act.emit("reporter", f"Attestation (HTML fallback): {html_path.name}")
    except (ImportError, OSError):
        pass
