"""#47 + #50 + #51 — Bug-bounty submission formatter + customer trust-center
page generator + pentest engagement-letter generator.

#47 — Format a Finding into the exact submission template each platform expects
#50 — Auto-generate a /security trust-center HTML page from a ScanReport
#51 — Output a template engagement letter for ad-hoc client pentests
"""
from __future__ import annotations

from pathlib import Path
from ..models import ScanReport


HACKERONE_TEMPLATE = """**Summary**: {title}

**Severity**: {severity}

**URL**: {url}

**Steps to reproduce**:
{evidence}

**Impact**:
This vulnerability allows {impact_summary}.

**Remediation**:
{remediation}

**Tags**: {tags}

---
*Submission generated by WPSecScan.*
"""

BUGCROWD_TEMPLATE = """## Vulnerability: {title}

**VRT**: {vrt}
**CVSS**: {cvss}
**URL**: {url}

### Description
{evidence}

### Proof of Concept
```
{poc}
```

### Mitigation
{remediation}
"""


def _safe(value: str) -> str:
    """Escape `{` / `}` so str.format() doesn't re-interpolate user content."""
    if value is None:
        return ""
    return str(value).replace("{", "{{").replace("}", "}}")


def format_for_hackerone(finding, *, check_id: str = "") -> str:
    sev = (finding.severity or "info").upper()
    return HACKERONE_TEMPLATE.format(
        title=_safe(finding.title),
        severity=sev,
        url=_safe(finding.url) or "(not specified)",
        evidence=_safe(finding.evidence) or "(not specified)",
        impact_summary={"critical": "remote code execution / full account takeover",
                         "high": "significant data exposure or privilege escalation",
                         "medium": "limited data exposure or denial-of-service",
                         "low": "minor information disclosure",
                         "info": "non-exploitable but suboptimal configuration"}.get(finding.severity, "?"),
        remediation=_safe(finding.remediation) or "See report.",
        tags=f"#wpsecscan #{check_id}" if check_id else "#wpsecscan",
    )


def format_for_bugcrowd(finding, *, check_id: str = "") -> str:
    return BUGCROWD_TEMPLATE.format(
        title=_safe(finding.title),
        vrt="see https://bugcrowd.com/vulnerability-rating-taxonomy",
        cvss="(compute manually)",
        url=_safe(finding.url) or "(not specified)",
        evidence=_safe(finding.evidence) or "(not specified)",
        poc=_safe(finding.evidence[:1000]) if finding.evidence else "(not specified)",
        remediation=_safe(finding.remediation) or "See report.",
    )


# #50 — customer-facing trust-center HTML page
def trust_center_html(report: ScanReport, *, brand: str = "Our Site") -> str:
    s = report.summary
    score = report.risk_score
    from ..risk import risk_grade
    return f"""<!doctype html>
<html><head><meta charset=utf-8><title>{brand} — security posture</title>
<style>body{{font-family:system-ui,sans-serif;max-width:760px;margin:40px auto;color:#222}}
.badge{{display:inline-block;padding:6px 14px;border-radius:6px;font-weight:600;color:white;background:#1f8a3c}}
.summary{{display:flex;gap:14px;margin:20px 0}}
.box{{flex:1;text-align:center;padding:18px;border-radius:6px;background:#f4f4f4}}</style>
</head><body>
<h1>{brand} — security posture</h1>
<p>Last scanned: <strong>{report.scanned_at}</strong></p>
<p>Overall security score: <span class="badge">{score}/100 (grade {risk_grade(score)})</span></p>
<div class=summary>
  <div class=box><strong>{s.get("critical",0)}</strong><br>critical</div>
  <div class=box><strong>{s.get("high",0)}</strong><br>high</div>
  <div class=box><strong>{s.get("medium",0)}</strong><br>medium</div>
  <div class=box><strong>{s.get("low",0)}</strong><br>low</div>
</div>
<h2>Standards we test against</h2>
<ul>
  <li>OWASP Top 10 (2021)</li>
  <li>MITRE ATT&amp;CK techniques</li>
  <li>PCI-DSS 4.0</li>
  <li>NIST SP 800-53 Rev. 5</li>
  <li>ISO/IEC 27001:2022</li>
  <li>CWE / D3FEND mappings</li>
</ul>
<h2>Contact</h2>
<p>Security issues: see our <a href="/.well-known/security.txt">security.txt</a></p>
<p><small>Generated by WPSecScan — defensive WordPress security scanner.</small></p>
</body></html>
"""


# #51 — pentest engagement letter
ENGAGEMENT_LETTER = """# Penetration Test Engagement Letter

**Between**: {vendor}
**And**: {client}
**Date**: {date}

## 1. Scope

The engagement covers automated + manual security testing of the following
assets, all owned by or operated on behalf of {client}:

- {targets}

The following are explicitly EXCLUDED from scope:
- Production payment systems handling live PCI data (unless separately scoped)
- DoS / DDoS testing
- Social-engineering / phishing of {client} staff
- Physical-security testing

## 2. Authorisation

{client} hereby authorises {vendor} to conduct security testing within the
scope above, using techniques up to and including:
- Reconnaissance (passive + active)
- Vulnerability scanning (automated + manual)
- Exploitation attempts on findings, proportionate to confirmation needs
- Post-exploitation enumeration sufficient to demonstrate impact

{vendor} shall not:
- Exfiltrate live customer data beyond what is needed to demonstrate finding
- Persist access after the engagement window
- Disclose findings to third parties before {client} agrees release

## 3. Deliverables

- Executive summary report (PDF) — within 5 business days of engagement end
- Technical findings report (HTML + JSON) — same day
- Re-test of remediated items — up to 30 days post-delivery

## 4. Engagement window

Start: {start_date}
End:   {end_date}

## 5. Communications

Primary contact ({vendor}): _____________________
Primary contact ({client}): _____________________
Emergency escalation:        _____________________

## 6. Liability

{vendor} carries professional liability insurance in the amount of
$___________. {client} acknowledges that defensive security testing
involves manipulation of production systems and that unanticipated
service disruption is a known risk.

---

Signed:

{vendor}: ________________________   Date: ________

{client}: ________________________   Date: ________
"""


def engagement_letter(*, vendor: str, client: str, targets: list[str],
                       date: str, start_date: str, end_date: str) -> str:
    return ENGAGEMENT_LETTER.format(
        vendor=vendor, client=client,
        targets="\n- ".join(targets),
        date=date, start_date=start_date, end_date=end_date,
    )
