"""I14 Native Jira / Linear / GitHub Issues export.

Generates the payloads in the shape each tracker's REST API accepts, but
does NOT post — we print the curl command so the user reviews + executes
intentionally. Auto-posting findings is too risky as a default; users with
write-tokens can pipe the output to bash if they trust it.

Tokens are read from env / CLI flags. The token is never written into the
output file — only into the curl command that the user runs locally.
"""
from __future__ import annotations

import html as _html
import json
from pathlib import Path

from ..models import ScanReport, SEVERITY_RANK


def _top_findings(report: ScanReport, min_sev: str = "medium") -> list[tuple[str, "Finding"]]:
    from ..models import Finding
    threshold = SEVERITY_RANK.get(min_sev, 2)
    out: list[tuple[str, Finding]] = []
    for r in report.results:
        for f in r.findings:
            if SEVERITY_RANK.get(f.severity, -1) >= threshold:
                out.append((r.check_id, f))
    out.sort(key=lambda x: -SEVERITY_RANK.get(x[1].severity, -1))
    return out


def _markdown_body(check_id: str, f) -> str:
    """Issue-friendly markdown for one finding."""
    lines = [
        f"**Severity:** {f.severity.upper()}",
        f"**Check:** `{check_id}`",
        f"**URL:** {f.url or '(not specified)'}",
        "",
        "## Evidence",
        "```",
        (f.evidence or "")[:2000],
        "```",
        "",
        "## Remediation",
        f.remediation or "(see scanner output)",
        "",
        "_Generated by WPSecScan._",
    ]
    return "\n".join(lines)


# ---------------- Jira ----------------

def jira_payloads(report: ScanReport, project_key: str, min_sev: str = "medium") -> list[dict]:
    """Build the list of Jira issue-create payloads. project_key like 'SEC' or 'INFRA'."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "fields": {
                "project": {"key": project_key},
                "summary": f"[{f.severity.upper()}] {f.title[:200]}",
                "description": _markdown_body(cid, f),
                "issuetype": {"name": "Bug"},
                "labels": ["wpsecscan", "security", f.severity],
            },
        })
    return out


def jira_curl_commands(report: ScanReport, project_key: str, base_url: str,
                       email: str, min_sev: str = "medium") -> list[str]:
    """Return one `curl` command per finding. base_url like 'https://yourorg.atlassian.net'.

    v2.8.1 B24 — use shlex.quote on every interpolated value. Pre-fix
    code used the homebrew `'\"'\"'` single-quote escape on the payload
    only, leaving backticks + ``$(...)`` substitution active in the
    `email`, `base_url`, and finding-title content. An operator who
    pasted the generated script into a shell with finding evidence
    containing ``$(rm -rf ~)`` would execute arbitrary commands. shlex.quote
    is POSIX-conforming and immune to backtick/dollar substitution.
    """
    import shlex as _shlex
    cmds = []
    for payload in jira_payloads(report, project_key, min_sev):
        body = json.dumps(payload)
        cmds.append(
            f"curl -sS -u {_shlex.quote(email + ':$JIRA_API_TOKEN')} "
            f"-H 'Content-Type: application/json' "
            f"-X POST {_shlex.quote(base_url + '/rest/api/2/issue')} "
            f"-d {_shlex.quote(body)}"
        )
    return cmds


# ---------------- Linear ----------------

def linear_payloads(report: ScanReport, team_id: str, min_sev: str = "medium") -> list[dict]:
    """Build Linear's GraphQL mutation payloads."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "query": "mutation IssueCreate($input: IssueCreateInput!) { issueCreate(input: $input) { success issue { id identifier url } } }",
            "variables": {
                "input": {
                    "teamId": team_id,
                    "title": f"[{f.severity.upper()}] {f.title[:200]}",
                    "description": _markdown_body(cid, f),
                    "labelIds": [],
                    "priority": {"critical": 1, "high": 2, "medium": 3, "low": 4, "info": 4}.get(f.severity, 3),
                },
            },
        })
    return out


def linear_curl_commands(report: ScanReport, team_id: str, min_sev: str = "medium") -> list[str]:
    cmds = []
    for payload in linear_payloads(report, team_id, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -H 'Authorization: $LINEAR_API_KEY' "
            f"-H 'Content-Type: application/json' "
            f"-X POST https://api.linear.app/graphql "
            f"-d '{body}'"
        )
    return cmds


# ---------------- GitHub Issues ----------------

def github_payloads(report: ScanReport, min_sev: str = "medium") -> list[dict]:
    """Build GitHub issue payloads (one per finding above the threshold)."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "title": f"[{f.severity.upper()}] {f.title[:200]}",
            "body": _markdown_body(cid, f),
            "labels": ["security", "wpsecscan", f.severity],
        })
    return out


def github_curl_commands(report: ScanReport, repo: str, min_sev: str = "medium") -> list[str]:
    """repo = 'owner/name'."""
    cmds = []
    for payload in github_payloads(report, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -H 'Authorization: Bearer $GITHUB_TOKEN' "
            f"-H 'Accept: application/vnd.github+json' "
            f"-X POST 'https://api.github.com/repos/{repo}/issues' "
            f"-d '{body}'"
        )
    return cmds


# ---------------- Notion ----------------

# Notion's database properties depend on the user's schema, so we keep the
# payload minimal: title (the only universally-required property type) plus
# a "children" block list containing the finding's markdown body. The
# database is expected to have a title column called "Name" (Notion's
# default). Users with richer schemas can replace this property dict with
# their own keys via the WPSECSCAN_NOTION_PROPS env var (a JSON dict of
# additional Notion property objects merged into every page payload).

_NOTION_VERSION = "2022-06-28"  # API stability tier; bumped by Notion when breaking


def notion_payloads(report: ScanReport, database_id: str,
                    title_property: str = "Name",
                    min_sev: str = "medium",
                    extra_props: dict | None = None) -> list[dict]:
    """Build Notion `pages.create` payloads (one per finding above the threshold).

    Args:
        database_id: the destination Notion database ID (32-hex with dashes).
        title_property: name of the title column in the database (Notion's
            default is "Name"; some users rename it to "Title" or "Finding").
        min_sev: cap findings at this severity.
        extra_props: optional dict of additional Notion property objects
            (e.g. select / multi-select / status) merged into every payload.
    """
    out: list[dict] = []
    for cid, f in _top_findings(report, min_sev):
        title_text = f"[{f.severity.upper()}] {f.title[:200]}"
        body_md = _markdown_body(cid, f)
        # Notion text blocks have a 2000-char limit per rich-text element;
        # split the markdown body across multiple paragraph blocks to stay
        # under the limit.
        chunks = [body_md[i:i + 1800] for i in range(0, len(body_md), 1800)] or [""]
        page_props: dict = {
            title_property: {
                "title": [{"type": "text", "text": {"content": title_text[:2000]}}]
            },
        }
        if extra_props:
            page_props.update(extra_props)
        payload = {
            "parent": {"database_id": database_id},
            "properties": page_props,
            "children": [
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"type": "text", "text": {"content": chunk}}]
                    },
                }
                for chunk in chunks
            ],
        }
        out.append(payload)
    return out


def notion_curl_commands(report: ScanReport, database_id: str,
                         title_property: str = "Name",
                         min_sev: str = "medium") -> list[str]:
    """Return one `curl` command per finding. Token reads from $NOTION_TOKEN."""
    cmds: list[str] = []
    for payload in notion_payloads(report, database_id, title_property, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -H 'Authorization: Bearer $NOTION_TOKEN' "
            f"-H 'Notion-Version: {_NOTION_VERSION}' "
            f"-H 'Content-Type: application/json' "
            f"-X POST 'https://api.notion.com/v1/pages' "
            f"-d '{body}'"
        )
    return cmds


# ---------------- Combined writer ----------------

def write(report: ScanReport, path: Path, *,
          jira_project: str | None = None,
          jira_email: str | None = None,
          jira_base: str | None = None,
          linear_team: str | None = None,
          github_repo: str | None = None,
          notion_db: str | None = None,
          notion_title_prop: str = "Name",
          min_sev: str = "medium") -> None:
    """Write a single shell script that contains curl commands for every
    configured tracker, with a sourced env-var preamble."""
    parts: list[str] = [
        "#!/usr/bin/env bash",
        "# WPSecScan issue export — review before running.",
        f"# Threshold: {min_sev}",
        f"# Target:    {report.target}",
        "#",
        "# Required env vars (set before running):",
        "#   JIRA_API_TOKEN, LINEAR_API_KEY, GITHUB_TOKEN, NOTION_TOKEN",
        "#",
        "set -euo pipefail",
        "",
    ]
    if jira_project and jira_email and jira_base:
        parts.append("# Jira issues")
        parts.extend(jira_curl_commands(report, jira_project, jira_base, jira_email, min_sev))
        parts.append("")
    if linear_team:
        parts.append("# Linear issues")
        parts.extend(linear_curl_commands(report, linear_team, min_sev))
        parts.append("")
    if github_repo:
        parts.append("# GitHub issues")
        parts.extend(github_curl_commands(report, github_repo, min_sev))
        parts.append("")
    if notion_db:
        parts.append("# Notion pages (DB ID: " + notion_db + ")")
        parts.extend(notion_curl_commands(report, notion_db, notion_title_prop, min_sev))
        parts.append("")
    # v2.8.3 H3 — atomic temp+rename via shared helper.
    from . import _atomic_write_text
    _atomic_write_text(path, "\n".join(parts))
