"""I14 Native Jira / Linear / GitHub Issues export.

Generates the payloads in the shape each tracker's REST API accepts, but
does NOT post — we print the curl command so the user reviews + executes
intentionally. Auto-posting findings is too risky as a default; users with
write-tokens can pipe the output to bash if they trust it.

Tokens are read from env / CLI flags. The token is never written into the
output file — only into the curl command that the user runs locally.
"""
from __future__ import annotations

import html as _html
import json
from pathlib import Path

from ..models import ScanReport, SEVERITY_RANK


def _top_findings(report: ScanReport, min_sev: str = "medium") -> list[tuple[str, "Finding"]]:
    from ..models import Finding
    threshold = SEVERITY_RANK.get(min_sev, 2)
    out: list[tuple[str, Finding]] = []
    for r in report.results:
        for f in r.findings:
            if SEVERITY_RANK.get(f.severity, -1) >= threshold:
                out.append((r.check_id, f))
    out.sort(key=lambda x: -SEVERITY_RANK.get(x[1].severity, -1))
    return out


def _markdown_body(check_id: str, f) -> str:
    """Issue-friendly markdown for one finding."""
    lines = [
        f"**Severity:** {f.severity.upper()}",
        f"**Check:** `{check_id}`",
        f"**URL:** {f.url or '(not specified)'}",
        "",
        "## Evidence",
        "```",
        (f.evidence or "")[:2000],
        "```",
        "",
        "## Remediation",
        f.remediation or "(see scanner output)",
        "",
        "_Generated by WPSecScan._",
    ]
    return "\n".join(lines)


# ---------------- Jira ----------------

def jira_payloads(report: ScanReport, project_key: str, min_sev: str = "medium") -> list[dict]:
    """Build the list of Jira issue-create payloads. project_key like 'SEC' or 'INFRA'."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "fields": {
                "project": {"key": project_key},
                "summary": f"[{f.severity.upper()}] {f.title[:200]}",
                "description": _markdown_body(cid, f),
                "issuetype": {"name": "Bug"},
                "labels": ["wpsecscan", "security", f.severity],
            },
        })
    return out


def jira_curl_commands(report: ScanReport, project_key: str, base_url: str,
                       email: str, min_sev: str = "medium") -> list[str]:
    """Return one `curl` command per finding. base_url like 'https://yourorg.atlassian.net'."""
    cmds = []
    for payload in jira_payloads(report, project_key, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -u '{email}:$JIRA_API_TOKEN' "
            f"-H 'Content-Type: application/json' "
            f"-X POST '{base_url}/rest/api/2/issue' "
            f"-d '{body}'"
        )
    return cmds


# ---------------- Linear ----------------

def linear_payloads(report: ScanReport, team_id: str, min_sev: str = "medium") -> list[dict]:
    """Build Linear's GraphQL mutation payloads."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "query": "mutation IssueCreate($input: IssueCreateInput!) { issueCreate(input: $input) { success issue { id identifier url } } }",
            "variables": {
                "input": {
                    "teamId": team_id,
                    "title": f"[{f.severity.upper()}] {f.title[:200]}",
                    "description": _markdown_body(cid, f),
                    "labelIds": [],
                    "priority": {"critical": 1, "high": 2, "medium": 3, "low": 4, "info": 4}.get(f.severity, 3),
                },
            },
        })
    return out


def linear_curl_commands(report: ScanReport, team_id: str, min_sev: str = "medium") -> list[str]:
    cmds = []
    for payload in linear_payloads(report, team_id, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -H 'Authorization: $LINEAR_API_KEY' "
            f"-H 'Content-Type: application/json' "
            f"-X POST https://api.linear.app/graphql "
            f"-d '{body}'"
        )
    return cmds


# ---------------- GitHub Issues ----------------

def github_payloads(report: ScanReport, min_sev: str = "medium") -> list[dict]:
    """Build GitHub issue payloads (one per finding above the threshold)."""
    out = []
    for cid, f in _top_findings(report, min_sev):
        out.append({
            "title": f"[{f.severity.upper()}] {f.title[:200]}",
            "body": _markdown_body(cid, f),
            "labels": ["security", "wpsecscan", f.severity],
        })
    return out


def github_curl_commands(report: ScanReport, repo: str, min_sev: str = "medium") -> list[str]:
    """repo = 'owner/name'."""
    cmds = []
    for payload in github_payloads(report, min_sev):
        body = json.dumps(payload).replace("'", "'\"'\"'")
        cmds.append(
            f"curl -sS -H 'Authorization: Bearer $GITHUB_TOKEN' "
            f"-H 'Accept: application/vnd.github+json' "
            f"-X POST 'https://api.github.com/repos/{repo}/issues' "
            f"-d '{body}'"
        )
    return cmds


# ---------------- Combined writer ----------------

def write(report: ScanReport, path: Path, *,
          jira_project: str | None = None,
          jira_email: str | None = None,
          jira_base: str | None = None,
          linear_team: str | None = None,
          github_repo: str | None = None,
          min_sev: str = "medium") -> None:
    """Write a single shell script that contains curl commands for every
    configured tracker, with a sourced env-var preamble."""
    parts: list[str] = [
        "#!/usr/bin/env bash",
        "# WPSecScan issue export — review before running.",
        f"# Threshold: {min_sev}",
        f"# Target:    {report.target}",
        "#",
        "# Required env vars (set before running):",
        "#   JIRA_API_TOKEN, LINEAR_API_KEY, GITHUB_TOKEN",
        "#",
        "set -euo pipefail",
        "",
    ]
    if jira_project and jira_email and jira_base:
        parts.append("# Jira issues")
        parts.extend(jira_curl_commands(report, jira_project, jira_base, jira_email, min_sev))
        parts.append("")
    if linear_team:
        parts.append("# Linear issues")
        parts.extend(linear_curl_commands(report, linear_team, min_sev))
        parts.append("")
    if github_repo:
        parts.append("# GitHub issues")
        parts.extend(github_curl_commands(report, github_repo, min_sev))
        parts.append("")
    path.write_text("\n".join(parts), encoding="utf-8")
