"""Custom-branding for the existing PDF reporter.

Round-64 #93 — extends `exec_pdf.py` with logo + colour customisation
via `~/.wpsecscan/brand.json`. Falls back to defaults when missing.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Branding:
    organization_name: str = "WPSecScan"
    logo_path: str | None = None
    primary_color: str = "#1976d2"
    accent_color: str = "#e65100"
    footer_text: str = "Generated by WPSecScan — defensive WP security scanner."

    @classmethod
    def load(cls) -> "Branding":
        home = Path(os.environ.get("WPSECSCAN_HOME") or (Path.home() / ".wpsecscan"))
        f = home / "brand.json"
        if not f.exists():
            return cls()
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return cls()
        return cls(
            organization_name=str(data.get("organization_name", cls.organization_name)),
            logo_path=data.get("logo_path"),
            primary_color=str(data.get("primary_color", cls.primary_color)),
            accent_color=str(data.get("accent_color", cls.accent_color)),
            footer_text=str(data.get("footer_text", cls.footer_text)),
        )

    def to_dict(self) -> dict:
        return {
            "organization_name": self.organization_name,
            "logo_path": self.logo_path,
            "primary_color": self.primary_color,
            "accent_color": self.accent_color,
            "footer_text": self.footer_text,
        }


def apply_to_pdf_styles(brand: Branding) -> dict:
    """Return a dict of style overrides that exec_pdf.py can read."""
    return {
        "title_color": brand.primary_color,
        "section_color": brand.accent_color,
        "logo": brand.logo_path,
        "footer": brand.footer_text,
        "organization": brand.organization_name,
    }
