"""Public scorecard page (opt-in).

Round-64 #92 — generates a static HTML page suitable for hosting on
GitHub Pages or similar. Shows ONLY summary statistics; no finding
detail. Opt-in: caller must pass `public=True` so we don't accidentally
leak findings.
"""
from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from pathlib import Path


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 700px; margin: 2em auto; padding: 1em; color: #222; }}
.grade {{ font-size: 4em; font-weight: bold; color: {grade_colour}; }}
table {{ border-collapse: collapse; width: 100%; margin-top: 1em; }}
th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
th {{ background: #f7f7f7; }}
.footer {{ color: #999; font-size: 0.85em; margin-top: 2em; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="grade">{grade}</p>
<p>Scanned: {scanned_at}</p>
<table>
<thead><tr><th>Severity</th><th>Count</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
<p class="footer">
Generated by <a href="https://github.com/bryanflowers/wpsecscan">WPSecScan</a>.
This page is intentionally public and contains no finding detail.
</p>
</body>
</html>
"""

_GRADE_COLOURS = {
    "A+": "#2e7d32", "A": "#388e3c", "B": "#fbc02d",
    "C": "#fb8c00", "D": "#e64a19", "F": "#b00020",
}


def _grade(summary: dict) -> str:
    if summary.get("critical", 0) > 0:
        return "F"
    if summary.get("high", 0) > 0:
        return "D"
    if summary.get("medium", 0) > 2:
        return "C"
    if summary.get("medium", 0) > 0:
        return "B"
    return "A+" if summary.get("low", 0) == 0 else "A"


def render_public_page(target: str, summary: dict, scanned_at: str | None = None, public: bool = False) -> str:
    if not public:
        raise ValueError("public_page must be opted into via public=True (defensive default)")
    grade = _grade(summary)
    rows = "\n".join(
        f"<tr><td>{escape(sev)}</td><td>{int(summary.get(sev, 0))}</td></tr>"
        for sev in ("critical", "high", "medium", "low", "info")
    )
    return _TEMPLATE.format(
        title=escape(f"Security scorecard — {target}"),
        grade=escape(grade),
        grade_colour=_GRADE_COLOURS.get(grade, "#777"),
        scanned_at=escape(scanned_at or datetime.now(tz=timezone.utc).isoformat()),
        rows=rows,
    )


def write_public_page(path: str, target: str, summary: dict, *, public: bool = False, scanned_at: str | None = None) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.is_symlink():
        p.unlink()
    # v2.8.3 H3 — atomic temp+rename via shared helper.
    from . import _atomic_write_text
    _atomic_write_text(p, render_public_page(target, summary, scanned_at, public=public))
