"""WAF rule-set fingerprinting.

Once the `waf` check has identified a WAF vendor (Cloudflare, AWS WAF,
Sucuri, Wordfence), this check sends a small differential battery to identify
which RULESET is active:
  - OWASP CRS 3.x vs 4.x (different blocking thresholds)
  - Cloudflare Managed Ruleset vs Custom (paranoia level)
  - AWS WAF Common vs Bot Control
  - Wordfence Premium vs Free (different rule counts)

Identification is informational; tells the user *what* protection is actually
running, not just *that* a WAF exists.
"""
from __future__ import annotations

from ..http import Client
from ..models import Finding

# (payload, what it tests, vendor signature in response)
PROBES = (
    ("/?test=1' OR '1'='1", "classic SQLi tautology",
     {"cloudflare": "challenge-platform", "sucuri": "blocked by Sucuri", "wordfence": "Generated by Wordfence",
      "akamai": "Access Denied", "aws": "Request blocked"}),
    ("/?test=<script>alert(1)</script>", "vanilla XSS",
     {"cloudflare": "challenge-platform", "sucuri": "blocked by Sucuri",
      "modsecurity": "ModSecurity", "owasp_crs": "Mandatory rule"}),
    ("/?test=../../../etc/passwd", "path traversal",
     {"modsecurity": "ModSecurity", "owasp_crs": "Mandatory rule",
      "cloudflare": "challenge-platform"}),
    ("/?test=cmd|whoami", "command injection",
     {"modsecurity": "ModSecurity", "owasp_crs": "Mandatory rule"}),
)


async def check(client: Client, ctx: dict) -> list[Finding]:
    findings: list[Finding] = []
    step = ctx.get("step") or (lambda _s: None)

    waf_list = ctx.get("shared", {}).get("waf") or []
    if not waf_list:
        findings.append(
            Finding(
                severity="info",
                title="WAF ruleset fingerprint skipped — no WAF detected",
                evidence="The `waf` check didn't fingerprint a WAF vendor.",
                remediation="No action.",
                url=ctx["target"],
            )
        )
        return findings

    detected_rulesets: set[str] = set()
    detected_blocking_strength: dict[str, int] = {"blocked": 0, "passed": 0}

    for payload_path, what_it_tests, sig_map in PROBES:
        step(f"WAF ruleset probe: {what_it_tests}...")
        r = await client.get(payload_path)
        if r is None:
            continue
        body = (r.text or "")[:8000].lower()
        # Strong-block markers
        if r.status_code in (403, 406, 419, 501, 999):
            detected_blocking_strength["blocked"] += 1
        else:
            detected_blocking_strength["passed"] += 1
        for ruleset, marker in sig_map.items():
            if marker.lower() in body:
                detected_rulesets.add(ruleset)

    block_rate = detected_blocking_strength["blocked"] / max(1, sum(detected_blocking_strength.values()))

    if not detected_rulesets and block_rate < 0.25:
        findings.append(
            Finding(
                severity="medium",
                title=f"WAF detected ({', '.join(waf_list)}) but ruleset appears weak",
                evidence=(
                    f"Blocked {detected_blocking_strength['blocked']}/"
                    f"{sum(detected_blocking_strength.values())} test payloads "
                    f"(block rate {block_rate:.0%}).\n"
                    "No fingerprintable strong ruleset (OWASP CRS, ModSecurity) in response bodies."
                ),
                remediation=(
                    "Your WAF detection might just be a CDN's bot-management layer, not an actual "
                    "application-layer ruleset. Enable a real WAF ruleset: Cloudflare Managed Rules, "
                    "AWS WAF Core, ModSecurity OWASP CRS, or Wordfence Premium."
                ),
                url=ctx["target"],
            )
        )
    else:
        sev = "info" if block_rate >= 0.75 else "low"
        findings.append(
            Finding(
                severity=sev,
                title=(
                    f"WAF ruleset fingerprint: {', '.join(detected_rulesets) or 'unidentified'}; "
                    f"block rate {block_rate:.0%}"
                ),
                evidence=(
                    f"WAF vendors detected (from `waf` check): {', '.join(waf_list)}\n"
                    f"Identified rulesets: {', '.join(detected_rulesets) or '(none — generic block)'}\n"
                    f"Blocked {detected_blocking_strength['blocked']}/"
                    f"{sum(detected_blocking_strength.values())} probes."
                ),
                remediation=(
                    "Your WAF is filtering OWASP-class attacks. Consider also:\n"
                    "  - Rate limiting on /wp-login.php (often a separate config)\n"
                    "  - Custom rules for plugins with known CVEs while waiting for patch"
                ),
                url=ctx["target"],
            )
        )
    return findings
