"""yarn.lock + pnpm-lock.yaml exposure audit.

Round-64 #61 — companion to package_lock_audit.py for the non-npm Node
lockfile formats. Yarn 1.x writes plain-text (custom format), Yarn 2+
writes YAML, pnpm writes YAML. The risk profile is identical to
package-lock.json: dependency disclosure + occasional auth-token leaks.
"""
from __future__ import annotations

import re

from ..http import Client
from ..models import Finding

_PROBE_PATHS = (
    "/yarn.lock",
    "/pnpm-lock.yaml",
    "/wp-content/yarn.lock",
    "/wp-content/pnpm-lock.yaml",
    "/wp-content/themes/yarn.lock",
)

# Same auth-token pattern as the npm check
_TOKEN_RE = re.compile(
    r'(npmjs\.org|nodejs\.org|github\.com|gitlab\.com)/[^"\s]*[?&]?(token|key|access_token)=([A-Za-z0-9_\-]{20,})',
    re.IGNORECASE,
)


def _looks_like_yarn_lock(body: str) -> bool:
    """yarn v1: line starts like  package@version:  with subsequent indented version/resolved blocks."""
    if not body:
        return False
    # quick signature
    return body.startswith("# THIS IS AN AUTOGENERATED FILE") or re.search(
        r'^[a-z0-9_@./-]+@[^:]+:\n\s+version "', body, re.MULTILINE
    ) is not None


def _looks_like_pnpm_lock(body: str) -> bool:
    """pnpm: YAML with lockfileVersion + packages: header"""
    return "lockfileVersion:" in body and "\npackages:" in body


async def check(client: Client, ctx: dict) -> list[Finding]:
    findings: list[Finding] = []
    step = ctx.get("step") or (lambda _s: None)

    for path in _PROBE_PATHS:
        step(f"probing {path}...")
        r = await client.get(path)
        if r is None or r.status_code != 200:
            continue
        body = r.text or ""
        if len(body) < 50:
            continue

        is_yarn = path.endswith("yarn.lock") and _looks_like_yarn_lock(body)
        is_pnpm = path.endswith("pnpm-lock.yaml") and _looks_like_pnpm_lock(body)
        if not (is_yarn or is_pnpm):
            continue

        kind = "yarn.lock" if is_yarn else "pnpm-lock.yaml"
        findings.append(
            Finding(
                severity="medium",
                title=f"{kind} exposed at {path}",
                evidence=f"GET {path} -> 200 ({len(body)} bytes); valid {kind} signature",
                remediation=(
                    "Block public access to Node lockfiles:\n"
                    "  Apache: <FilesMatch \"^(yarn|pnpm)-?(lock)?\\.(ya?ml|lock)$\"> Require all denied </FilesMatch>\n"
                    "  Nginx:  location ~* ^/(yarn|pnpm)-?(lock)?\\.(ya?ml|lock)$ { deny all; }\n"
                    "Then audit deps with `yarn audit` / `pnpm audit`."
                ),
                url=client.url(path),
            )
        )

        # Token leak check
        m = _TOKEN_RE.search(body)
        if m:
            findings.append(
                Finding(
                    severity="critical",
                    title="Registry auth token leaked in lockfile resolved URL",
                    evidence=f"Token pattern in {path}: {m.group(0)[:80]}...",
                    remediation="Rotate the token IMMEDIATELY. Block public access to the lockfile. Consider a secret scanner in CI to prevent recurrence.",
                    url=client.url(path),
                )
            )

    return findings
